name: Keep Render Warm

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://mini-games-backend-h7ab.onrender.com/warmup
